### ISSUE TITLE
Status migration question

### ISSUE THREAD

**Issue by marcinpilarczyk** [mittsh/freshdesk-zendesk-migration#2]
Hi,

In this part:
status_migration={
        8:('pending', 'pending-for-release',)

What exactly "8" means? It's not clear to me how to format it if I have several custom statuses in FD.

Thanks
Marcin

**Comment by mittsh** [comment]
@marcinpilarczyk If I remember well, it's the Freshdesk status for _pending_. So it assigns the `pending`, `pending-on-gitub` tags.

**Comment by marcinpilarczyk** [comment]
Could you advice me on how to add additional entries?

I'm trying this:

status_migration={
                        6:('pending','waiting-for-customer'),
                        7:('hold','waiting-for-3rd-party'),
                        8:{'hold','in-development')
                }

But getting a syntax error.

**Comment by mittsh** [comment]
@marcinpilarczyk As I mentioned on [the previous issue](https://github.com/mittsh/freshdesk-zendesk-migration/issues/1#issuecomment-39860062) I'm not involved anymore on this project unfortunately... Sorry I can't help much :(

**Comment by marcinpilarczyk** [comment]
Ok, no problem. i was just hoping you remember something about the format :)

**Comment by mittsh** [comment]
Ohh I see , you're doing a small Python syntax error: here's the right one:

``` python
status_migration={
  6:('pending','waiting-for-customer'),
  7:('hold','waiting-for-3rd-party'),
  8:('hold','in-development'),
}
```
